### ISSUE TITLE
No checkpoint file

### ISSUE THREAD

**Issue by ixanezis** [2Bear/othello-zero#1]
In order to use checkpoints files successfully, there must be something like a 'checkpoint' file in protobuf format as well... Didn't find it in checkpoint.zip

**Comment by 2Bear** [comment]
The **checkpoint** file is just a bookmark file.
You can create it manually.

Create a new text file named **checkpoint**.
Edit it. Here is a example, just one line:
```
model_checkpoint_path: "v117-14797350"
```
You can replace `v117-14797350` with any checkpoint name such as `v001-49150`.
In this way, you can choose different checkpoints to restore, and compare them.

Best.

**Comment by ixanezis** [comment]
Thanks. That has worked.
